name: Updating Arch Linux Docker image

on:
  schedule:
    - cron:  '0 0 * * 0'


jobs:
  build-archlinux:
    runs-on: ubuntu-latest
    timeout-minutes: 600
    
    steps:
    - name: Checkout!
      uses: actions/checkout@v2

    - name: Then set up Tailscale
      uses: tailscale/github-action@v1
      with:
        authkey: ${{ secrets.TAILSCALE_AUTHKEY }}
    
    - name: Build and push Arch Linux Docker image
      uses: mr-smithers-excellent/docker-build-push@v5
      with:
        image: sprucecellodev125/custom-gitpod-image
        tags: archlinux, latest
        registry: ghcr.io
        dockerfile: .gitpod.Dockerfile
        username: ${{ secrets.CR_USER }}
        password: ${{ secrets.CR_PAT }}