name: Updating Debian Linux Docker image

on:
  schedule:
    - cron:  '0 0 1 * *'

jobs:
  build-debian:
    runs-on: ubuntu-latest
    timeout-minutes: 600
    
    steps:
    - name: Checkout first
      uses: actions/checkout@v2

    - name: Then set up Tailscale
      uses: tailscale/github-action@v1
      with:
        authkey: ${{ secrets.TAILSCALE_AUTHKEY }}
    
    - name: Build and push Debian Docker image
      uses: mr-smithers-excellent/docker-build-push@v5
      with:
        image: sprucecellodev125/custom-gitpod-image
        tags: debian
        registry: ghcr.io
        dockerfile: .gitpod.debian.Dockerfile
        username: ${{ secrets.CR_USER }}
        password: ${{ secrets.CR_PAT }}